package ie.gmit.sw;

import java.rmi.Naming;

import ie.gmit.sw.VigenereBreaker;

public class Client {
	
	public static void main(String[] args) throws Exception {
		/*
		 * This stuff needs to be in your tomcat app
		 */
		VigenereBreaker vb = (VigenereBreaker) Naming.lookup("///cypher-service");
		
		vb.decrypt("YUNJBNANJMCQNJBBRPWVNWCMNBLARYCRXWJWMBLQNMDUNLJANODUUHJWMMXWXCKNMJDWCNMJUUXOCQNFNKLURNWCODWLCRXWJURCHRWLUDMRWPYNARXMRLYXUURWPRBJUANJMHJEJRUJKUNRWCQNURBCXOANBXDALNBKNUXFCQNANBXDALNBJUBXRWLUDMNJWRVYUNVNWCJCRXWXOCQNERPNWNANLHYQNAJWMJLUJBBLJYJKUNXONWDVNAJCRWPJBNCXOTNHBCQNVJRWKXMHXOFXATCXKNLXVYUNCNMKHHXDRBCXRVYUNVNWCCQNJBHWLQAXWXDBVNBBJPNZDNDNBJWMCQNAVRBNAERLNRJUBXFRUUYAXERMNJFXATBQXYCXPNCHXDJUUBCJACNMFRCQCQNJBBRPWVNWC", 4);
		//String result = vb.decrypt("FNUUYARWLNBXPNWXJJWMUDLLJJANWXFSDBCOJVRUHNBCJCNBXOCQNKDXWJYJACNBKDCRFJAWHXDROHXDMXWCCNUUVNCQJCCQRBVNJWBFJAROHXDBCRUUCAHCXMNONWMCQNRWOJVRNBJWMQXAAXABYNAYNCAJCNMKHCQJC", 4);
	}
}
